Worker.create!([
  {rut: "11632422-9", name: "RICARDO MARCELO MILLAN GUTIERREZ", unity: nil, charge: "INTENDENTE", email: "RMILLAN@GOREDELOSRIOS.CL", observation: nil},
  {rut: "14081566-7", name: "LEONARDO JUAN FAÚNDEZ MARTÍNEZ", unity: "JEFE DIVISIÓN PLANIFICACIÓN Y DESARROLLO REGIONAL", charge: "DIVISIóN DE PLANIFICACIóN Y DESARROLLO REGIONAL", email: "lfaundez@goredelosrios.cl", observation: nil},
  {rut: "14281829-9", name: "PEDRO GACITUA GALLARDO", unity: "JEFE DIVISIÓN ADMINISTRACIÓN Y FINANZAS", charge: "DIVISIóN DE ADMINISTRACIóN Y FINANZAS", email: "pgacitua@goredelosrios.cl", observation: nil},
  {rut: "9346986-0", name: "HECTOR ALEJANDRO GALLARDO VIDAL", unity: "SECTORIALISTA ", charge: "DEPARTAMENTO DE GESTIóN E INVERSIONES", email: "agallardo@goredelosrios.cl", observation: nil},
  {rut: "8024431-2", name: "JUAN CARLOS CASTILLO AVILA", unity: "ANALISTA DE INVERSIONES", charge: "DEPARTAMENTO DE GESTIóN E INVERSIONES", email: "jcastillo@goredelosrios.cl", observation: nil},
  {rut: "9393603-5", name: "FERNANDO EDUARDO PICHAUD SANHUEZA", unity: "ASESOR CONSEJO REGIONAL", charge: "SECRETARíA EJECUTIVA CONSEJO REGIONAL", email: "fpichaud@goredelosrios.cl", observation: nil},
  {rut: "12994202-9", name: "RODRIGO GONZALO ARAVENA BUSTAMANTE", unity: "ENCARGADO UNIDAD DE CONTROL ESTRATÉGICO INSTITUCIONAL", charge: "UNIDAD DE GESTIóN ESTRATéGICA INSTITUCIONAL", email: "raravena@goredelosrios.cl", observation: nil},
  {rut: "8122766-7", name: "SERGIO ALFREDO VILLAVICENCIO RIQUELME", unity: "PROGRAMADOR FNDR", charge: "DEPARTAMENTO DE PRESUPUESTO", email: "svillavicencio@goredelosrios.cl", observation: nil},
  {rut: "8904650-5", name: "MAURICIO FABIAN PEÑA VERA", unity: "PROFESIONAL EN PLANIFICACIÓN TERRITORIAL", charge: "UNIDAD DE ORDENAMIENTO Y GESTIóN TERRITORIAL", email: "mpena@goredelosrios.cl", observation: nil},
  {rut: "7465573-4", name: "ARMIN RODRIGO FERNANDEZ MARDONES", unity: "SECTORIALISTA DE INVERSIONES", charge: "DEPARTAMENTO DE GESTIóN E INVERSIONES", email: "afernandez@goredelosrios.cl", observation: nil},
  {rut: "11809192-2", name: "MARCELO ALEJANDRO ROMERO CONTRERAS", unity: "PROFESIONAL DE LA UNIDAD DE AUDITORÍA INTERNA", charge: "UNIDAD DE AUDITORIA INTERNA", email: "mromero@goredelosrios.cl", observation: nil},
  {rut: "14494740-1", name: "VICTOR FRANCISCO ALVAREZ CULUN", unity: "UNIDAD FRIL", charge: "UNIDAD FRIL", email: "valvarez@goredelosrios.cl", observation: nil},
  {rut: "14081059-2", name: "JUAN DANIEL TEJEDA PEREZ", unity: "ADMINISTRATIVO SAIP- OFICINA DE PARTES", charge: "OFICINA DE PARTES", email: "jtejeda@goredelosrios.cl", observation: nil},
  {rut: "7030512-7", name: "JORGE AUGUSTO AGUILA SEPULVEDA", unity: "ADMINISTRATIVO GABINETE", charge: "INTENDENTE", email: "jaguila@goredelosrios.cl", observation: nil},
  {rut: "10367943-5", name: "PATRICIA MORANO BÜCHNER", unity: "INTENDENTE", charge: "INTENDENTE", email: nil, observation: nil},
  {rut: "14084251-6", name: "YEISSE LORENA KIESSLING SALAS", unity: "JEFE DIVISIÓN DE ANÁLISIS Y CONTROL DE GESTIÓN ", charge: "DIVISIóN DE ANáLISIS Y CONTROL DE GESTIóN", email: "lkiessling@goredelosrios.cl", observation: nil},
  {rut: "10872160-K", name: "PAOLA MARCELA HERMOSILLA BUCAREY", unity: "ENCARGADA DEPARTAMENTO JURÍDICO", charge: "DEPARTAMENTO JURíDICO", email: "phermosilla@goredelosrios.cl", observation: nil},
  {rut: "10709653-1", name: "CECILIA CAMILA QUINTANA BINIMELIS", unity: "ENCARGADA DEPARTAMENTO DE PLANIFICACIÓN ESTRATÉGICA", charge: "DEPARTAMENTO DE PLANIFICACIóN ESTRATéGICA", email: "cquintana@goredelosrios.cl", observation: nil},
  {rut: "13818098-0", name: "YESSICA ANDREA GUTIERREZ RODRIGUEZ", unity: "PROFESIONAL ", charge: "DEPARTAMENTO DE FINANZAS", email: "ygutierrez@goredelosrios.cl", observation: nil},
  {rut: "11702896-8", name: "ANGELICA BEATRIZ PARRA SOLIS", unity: "ENCARGADA UNIDAD DE FOMENTO PRODUCTIVO Y DESARROLLO TECNOLÓGICO ", charge: "DIVISIóN DE PLANIFICACIóN Y DESARROLLO REGIONAL", email: "aparra@goredelosrios.cl", observation: nil},
  {rut: "12746786-2", name: "CAMILA FERNANDA MATUS ZUNIGA", unity: "ABOGADO DEPARTAMENTO JURIDICO", charge: "DEPARTAMENTO JURíDICO", email: "cmatus@goredelosrios.cl", observation: nil},
  {rut: "12712985-1", name: "MARIA SOLANGE PALAVECINO MEDINA", unity: "SECTORIALISTA ", charge: "DEPARTAMENTO DE GESTIóN E INVERSIONES", email: "mpalavecino@goredelosrios.cl", observation: nil},
  {rut: "9655597-0", name: "JUANA NELIDA SCHNEIDER GATICA", unity: "UNIDAD FRIL", charge: "UNIDAD FRIL", email: "jschneider@goredelosrios.cl", observation: nil},
  {rut: "11409475-7", name: "ERWIN HERNÁN ROSAS ALARCON", unity: "ADMINISTRADOR REGIONAL", charge: "GABINETE Y COMUNICACIóN", email: "erosas@goredelosrios.cl", observation: nil},
  {rut: "5336461-6", name: "RODOLFO ALBERTO PEÑA ZORICH", unity: "ANALISTA DE INVERSIONES", charge: "DEPARTAMENTO DE GESTIóN E INVERSIONES", email: "rpena@goredelosrios.cl", observation: nil},
  {rut: "9334750-1", name: "CESAR JOSE PEREZ SEPULVEDA", unity: "ENCARGADO DEPARTAMENTO DE FINANZAS", charge: "DEPARTAMENTO DE FINANZAS", email: "cperez@goredelosrios.cl", observation: nil},
  {rut: "11969617-8", name: "JORGE LUIS BALBOA TORO", unity: "ENCARGADO DEPARTAMENTO DE DESARROLLO ECONÓMICO-SOCIAL", charge: "DEPARTAMENTO DE DESARROLLO ECONóMICO Y SOCIAL", email: "jbalboa@goredelosrios.cl", observation: nil},
  {rut: "13112066-4", name: "JOEL ANTONIO DURÁN TROPPA", unity: "ENCARGADO DE UNIDAD DE FONDOS REGIONALES DE INVERSIÓN LOCAL", charge: "UNIDAD FRIL", email: "jduran@goredelosrios.cl", observation: nil},
  {rut: "12644519-9", name: "MAURICIO ALEJANDRO JELVES PEREZ", unity: "ENCARGADO DE LA UNIDAD DE ANÁLISIS Y COORDINACIÓN DE LA INVERSIÓN REGIONAL", charge: "UNIDAD DE ANáLISIS Y COORDINACIóN DE INVERSIóN REGIONAL", email: "mjelves@goredelosrios.cl", observation: nil},
  {rut: "13085610-1", name: "LUIS PATRICIO ACUM SALINAS", unity: "ENCARGADO UNIDAD DE INFORMATICA", charge: "UNIDAD DE INFORMáTICA", email: "pacum@goredelosrios.cl", observation: nil},
  {rut: "12373269-3", name: "CESAR ALBERTO ACUÑA LEAL", unity: "PROFESIONAL ANALISTA DE SISTEMAS DE INFORMACIÓN TERRITORIAL GEOGRÁFICO", charge: "DIVISIóN DE PLANIFICACIóN Y DESARROLLO REGIONAL", email: "cacuna@goredelosrios.cl", observation: nil},
  {rut: "5585881-0", name: "RODRIGO CARLOS BÄHRE VOGEL", unity: "ENCARGADO UNIDAD REGIONAL DE ASUNTOS INTERNACIONALES", charge: "UNIDAD REGIONAL DE ASUNTOS INTERNACIONALES", email: "rbahre@goredelosrios.cl", observation: nil},
  {rut: "12746855-9", name: "MARCO ANTONIO CASAS PACHECO", unity: "ANALISTA DE INVERSION", charge: "DEPARTAMENTO DE GESTIóN E INVERSIONES", email: "mcasas@goredelosrios.cl", observation: nil},
  {rut: "13710033-9", name: "PATRICIO FABIAN ROMERO PEÑA", unity: "ENCARGADO UNIDAD DE GESTIÓN INFORMACIÓN TERRITORIAL (UGIT)", charge: "UNIDAD DE GESTIóN DE INFORMACIóN TERRITORIAL", email: "promero@goredelosrios.cl", observation: nil},
  {rut: "5884073-4", name: "VICTOR HUGO VELASQUEZ VALENZUELA", unity: "PROFESIONAL DEPTO. FINANZAS", charge: "DEPARTAMENTO DE FINANZAS", email: "vvelasquez@goredelosrios.cl", observation: nil},
  {rut: "4119378-6", name: "CECIL DELFIN ZUÑIGA JIMENEZ", unity: "MIEMBRO DEL COMITE DE HIGIENE Y SEGURIDAD", charge: "UNIDAD DE SUBVENCIONES", email: "czuniga@goredelosrios.cl", observation: nil},
  {rut: "16790137-9", name: "NICOLÁS ANDRÉS GUIÑEZ LÓPEZ", unity: "UNIDAD DE ORDENAMIENTO TERRITORIAL", charge: "DIVISIóN DE PLANIFICACIóN Y DESARROLLO REGIONAL", email: "nguinez@goredelosrios.cl", observation: nil},
  {rut: "15261499-3", name: "ALVARO GONZALO SARAVIA SARAVIA", unity: "PROFESIONAL UNIDAD DE ADQUISICIONES", charge: "UNIDAD DE ADQUISICIONES", email: "asaravia@goredelosrios.cl", observation: nil},
  {rut: "16563689-9", name: "CARLOS MARCIAL BAEZA BAEZA", unity: "ASESOR JURÍDICO EN DEPORTE Y CULTURA", charge: "UNIDAD DE SUBVENCIONES", email: "CARLOSBAEZABAEZA@GMAIL.COM", observation: nil},
  {rut: "15548958-8", name: "JAVIER ALEJANDRO HERNÁNDEZ  SEPÚLVEDA", unity: "ABOGADO DEPARTAMENTO JURIDICO", charge: "DEPARTAMENTO JURíDICO", email: "jhernandez@goredelosrios.cl", observation: nil},
  {rut: "12994676-8", name: "JOSE PATRICIO RIQUELME ROSAS", unity: "PROFESIONAL DEPARTAMENTO FINANZAS", charge: "DEPARTAMENTO DE FINANZAS", email: "jriquelme@goredelosrios.cl", observation: nil},
  {rut: "14346111-4", name: "FELIPE ANDRÉS SCHULTZ OYARZÚN", unity: "PROFESIONAL RESIDUOS SÓLIDOS", charge: "PROGRAMA RESIDUOS SóLIDOS", email: "faschultz@goredelosrios.cl", observation: nil},
  {rut: "12747824-4", name: "JUAN PATRICIO CABRERA SOLIS", unity: "ASESOR INFORMATICA", charge: "UNIDAD DE INFORMáTICA", email: "pcabrera@goredelosrios.cl", observation: nil},
  {rut: "14461547-6", name: "CHRISTIAN MARCELO BURGOS AMOYADO", unity: "TESORERO PROGRAMA 01", charge: "DEPARTAMENTO DE FINANZAS", email: "cburgos@goredelosrios.cl", observation: nil},
  {rut: "7948538-1", name: "ADOLFO GABRIEL PARDO SOTO", unity: "ADMINISTRATIVO SAIP- OFICINA DE PARTES", charge: "OFICINA DE PARTES", email: "apardo@goredelosrios.cl", observation: nil},
  {rut: "15292215-9", name: "ARMANDO JOHAN ORTEGA CHIGUAY", unity: "ADMINISTRATIVO SECRETARÍA EJECUTIVA DEL CONSEJO REGIONAL", charge: "SECRETARíA EJECUTIVA CONSEJO REGIONAL", email: "aortega@goredelosrios.cl", observation: nil},
  {rut: "15547912-4", name: "JOSE RAMON SEGOVIA RUIZ", unity: "ENCARGADO DE INVENTARIO Y APOYO ADM. UNIDAD DE SS. GENERALES", charge: "UNIDAD DE SERVICIOS GENERALES", email: "jsegovia@goredelosrios.cl", observation: nil},
  {rut: "14516432-K", name: "ERIC WALDO VIDAL PEREZ", unity: "ADMINISTRATIVO", charge: "UNIDAD DE SERVICIOS GENERALES", email: "evidal@goredelosrios.cl", observation: nil},
  {rut: "7421079-1", name: "RICARDO HERNAN BASSO BAHAMONDES", unity: "CONDUCTOR", charge: "CONDUCTORES", email: "rbasso@goredelosrios.cl", observation: nil},
  {rut: "11425380-4", name: "MARCELO EDUARDO CRISOSTOMO FUENTES", unity: "CONDUCTOR", charge: "CONDUCTORES", email: "mcrisostomo@goredelosrios.cl", observation: nil},
  {rut: "10389542-1", name: "JUAN CARLOS MONTECINOS VITO", unity: "ADMINISTRATIVO DIVISIóN ADMINISTRACIóN Y FINANZAS", charge: "UNIDAD DE SERVICIOS GENERALES", email: "jmontecinos@goredelosrios.cl", observation: nil},
  {rut: "10507387-9", name: "CLAUDIO ALBERTO REYES VARGAS", unity: "CONDUCTOR", charge: "CONDUCTORES", email: "creyes@goredelosrios.cl", observation: nil},
  {rut: "14280814-5", name: "WALDEMAR ANDRES REYES MADRID", unity: "ADMINISTRATIVO", charge: "UNIDAD DE SERVICIOS GENERALES", email: "wreyes@goredelosrios.cl", observation: nil},
  {rut: "11115347-7", name: "KARIM LISSETTE BERTIN GUARDA", unity: "ANALISTA DE INVERSIONES", charge: "DEPARTAMENTO DE GESTIóN E INVERSIONES", email: "kbertin@goredelosrios.cl", observation: nil},
  {rut: "8653178-K", name: "EDITH HAYDEE MONARDEZ BALCAZAR", unity: "ANALISTA DE INVERSIONES", charge: "DEPARTAMENTO DE GESTIóN E INVERSIONES", email: "emonardez@goredelosrios.cl", observation: nil},
  {rut: "13817897-8", name: "MARILA LORETO BARRIENTOS TRIVIÑOS", unity: "PROFESIONAL DE APOYO A MUNICIPIOS Y PREINVERSION", charge: "UNIDAD DE ANáLISIS Y COORDINACIóN DE INVERSIóN REGIONAL", email: "mbarrientos@goredelosrios.cl", observation: nil},
  {rut: "13905957-3", name: "MARJOLAINE CELIS LINNEBRINK", unity: "ANALISTA DE INVERSIONES", charge: "DEPARTAMENTO DE GESTIóN E INVERSIONES", email: "mcelis@goredelosrios.cl", observation: nil},
  {rut: "14081628-0", name: "LILIAN EUGENIA CERDA SOTO", unity: "ENCARGADA DEPTO. DE PERSONAL", charge: "DEPARTAMENTO DE PERSONAL", email: "lcerda@goredelosrios.cl", observation: nil},
  {rut: "13323500-0", name: "SANDRA ELIZABETH MARLENE MANSILLA TORRES", unity: "ANALISTA DE INVERSIONES", charge: "DEPARTAMENTO DE GESTIóN E INVERSIONES", email: "smansilla@goredelosrios.cl", observation: nil},
  {rut: "21730016-9", name: "VALENTINA MARISOL MEDIAVILLA PINEDA", unity: "MIEMBRO DEL COMITÉ PARITARIO DE HIGIENE Y SEGURIDAD ", charge: "DIVISIóN DE PLANIFICACIóN Y DESARROLLO REGIONAL", email: "vmediavilla@goredelosrios.cl", observation: nil},
  {rut: "9911874-1", name: "ELISA GABRIELA SOTO IDE", unity: "PROFESIONAL DE APOYO A MUNICIPIOS Y PREINVERSION", charge: "UNIDAD DE ANáLISIS Y COORDINACIóN DE INVERSIóN REGIONAL", email: "esoto@goredelosrios.cl", observation: nil},
  {rut: "13453344-7", name: "XIMENA VANESSA SUAREZ ORTEGA", unity: "ANALISTA DE INVERSIONES", charge: "DEPARTAMENTO DE GESTIóN E INVERSIONES", email: "xsuarez@goredelosrios.cl", observation: nil},
  {rut: "13061004-8", name: "CECILIA DEL CARMEN CANDIA MANSILLA", unity: "ENCARGADO DE SERVICIOS GENERALES", charge: "UNIDAD DE SERVICIOS GENERALES", email: "ccandia@goredelosrios.cl", observation: nil},
  {rut: "12748010-9", name: "CLAUDIA XIMENA JARA RIVAS", unity: "PROFESIONAL ENGARGADA PROGRAMA 02", charge: "DEPARTAMENTO DE FINANZAS", email: "cjara@goredelosrios.cl", observation: nil},
  {rut: "12430714-7", name: "ERNA VIVIANA RIVAS LOVERA", unity: "ENCARGADA UNIDAD DE ADQUISICIONES", charge: "UNIDAD DE ADQUISICIONES", email: "vrivas@goredelosrios.cl", observation: nil},
  {rut: "13520017-4", name: "ANGELA MAGDALENA RODRÍGUEZ RODRÍGUEZ", unity: "ENCARGADA UNIDAD DE SUBVENCIONES", charge: "UNIDAD DE SUBVENCIONES", email: "arodriguez@goredelosrios.cl", observation: nil},
  {rut: "13737582-6", name: "ALEJANDRA ISABEL MOLL PAILLACAR", unity: "APOYO PROGRAMADOR FNDR", charge: "DEPARTAMENTO DE PRESUPUESTO", email: "amoll@goredelosrios.cl", observation: nil},
  {rut: "9316789-9", name: "XIMENA CAROLINA CARO MUÑOZ", unity: "ANALISTA DE INVERSIÓN", charge: "DIVISIóN DE ANáLISIS Y CONTROL DE GESTIóN", email: "xcaro@goredelosrios.cl", observation: nil},
  {rut: "13627185-7", name: "PATRICIA ALEJANDRA DURAN SEPULVEDA", unity: "PROFESIONAL PROGRAMA PUESTA EN VALOR DEL PATRIMONIO", charge: "PROGRAMA DE PUESTA EN VALOR DEL PATRIMONIO", email: "pduran@goredelosrios.cl", observation: nil},
  {rut: "12747585-7", name: "VERONICA ALEJANDRA HENRIQUEZ DELGADO", unity: "PROFESIONAL DEPARTAMENTO DE PERSONAL", charge: "DEPARTAMENTO DE PERSONAL", email: "vhenriquez@goredelosrios.cl", observation: nil},
  {rut: "12390115-0", name: "SANDRA ADELINA PEREZ GUZMAN", unity: "PROFESIONAL UNIDAD INFORMATICA", charge: "UNIDAD DE INFORMáTICA", email: "sperez@goredelosrios.cl", observation: nil},
  {rut: "12201378-2", name: "INGRID BEATRIZ TORRES FARIAS", unity: "PROFESIONAL DEPTO. DE PERSONAL", charge: "DEPARTAMENTO DE PERSONAL", email: "itorres@goredelosrios.cl", observation: nil},
  {rut: "16564554-5", name: "ESTEFANI MARION BAIMA SOLIS", unity: "UNIDAD DE SUBVENCIONES", charge: "UNIDAD DE SUBVENCIONES", email: "ebaima@goredelosrios.cl", observation: nil},
  {rut: "13319209-3", name: "YENNY PAOLA MENDEZ ROMERO", unity: "SECRETARIA SECRETARÍA EJECUTIVA DEL CONSEJO REGIONAL", charge: "SECRETARíA EJECUTIVA CONSEJO REGIONAL", email: "ymendez@goredelosrios.cl", observation: nil},
  {rut: "17201050-4", name: "ANDREA PAZ RAMIREZ PARRA", unity: "PERIODISTA GABINETE Y CONSEJO REGIONAL", charge: "SECRETARíA EJECUTIVA CONSEJO REGIONAL", email: "aramirez@goredelosrios.cl", observation: nil},
  {rut: "12749073-2", name: "TAMARA ANGELICA ARAYA GARAY", unity: "DISEÑADOR GRÁFICO Y PUBLICITARIO", charge: "UNIDAD DE INFORMáTICA", email: "taraya@goredelosrios.cl", observation: nil},
  {rut: "13283038-k", name: "SILVIA CAROLINA MARTÍNEZ MONTOYA", unity: "ADMINISTRATIVO UNIDAD DE ADQUISICIONES", charge: "UNIDAD DE ADQUISICIONES", email: "smartinez@goredelosrios.cl", observation: nil},
  {rut: "16563913-8", name: "ZOILA MAURA REYES SAEZ", unity: "SECRETARIA UNIDAD DE CULTURA", charge: "UNIDAD DE SUBVENCIONES", email: "zreyes@goredelosrios.cl", observation: nil},
  {rut: "7478954-4", name: "PATRICIA HELIA ZAPATA CANCINO", unity: "ADMINISTRATIVA UNIDAD FRIL", charge: "UNIDAD FRIL", email: "pzapata@goredelosrios.cl", observation: nil},
  {rut: "7498004-K", name: "CLARA ROSA CARCAMO HERMOSILLA", unity: "ADMINISTRATIVO", charge: "DIVISIóN DE PLANIFICACIóN Y DESARROLLO REGIONAL", email: " DIVISIÓN DE PLANIFICACIÓN Y DESARROLLO REGIONAL", observation: "rcarcamo@goredelosrios.cl"},
  {rut: "13847026-1", name: "ANA PATRICIA JARA MARTINEZ", unity: "SECRETARIA JEFE DIVISIÓN DE PLANIFICACIÓN Y DESARROLLO REGIONAL", charge: "DIVISIóN DE PLANIFICACIóN Y DESARROLLO REGIONAL", email: "ajara@goredelosrios.cl", observation: nil},
  {rut: "10798045-8", name: "RINA VIRGINIA RIVERA SALAZAR", unity: "SECRETARIA JEFE DAF", charge: "DIVISIóN DE ADMINISTRACIóN Y FINANZAS", email: "rrivera@goredelosrios.cl", observation: nil},
  {rut: "12480871-5", name: "CARMEN GLORIA VARGAS ROJAS", unity: "ADMINISTRATIVA UNIDAD DE DEPORTES", charge: "UNIDAD DE SUBVENCIONES", email: "cvargas@goredelosrios.cl", observation: nil},
  {rut: "15293216-2", name: "CAROLINA VIOLETA VILLANUEVA ATERO", unity: "SECRETARIA DIVISIÓN ANALISIS", charge: "DIVISIóN DE ANáLISIS Y CONTROL DE GESTIóN", email: "cvillanueva@goredelosrios.cl", observation: nil},
  {rut: "7468831-4", name: "GUISELA SILVANA GAH CARILEO", unity: "PARTICIPACIÓN CIUDADANA", charge: "UNIDAD DE PARTICIPACIóN CIUDADANA", email: "GGAH@GOREDELOSRIOS.CL", observation: nil},
  {rut: "17125066-8", name: "CRISTOBAL PATRICIO SANDOVAL AGUERO", unity: "ENCARGADO UNIDAD DE PARTICIPACIÓN CIUDADANA", charge: "UNIDAD DE PARTICIPACIóN CIUDADANA", email: "csandoval@goredelosrios.cl", observation: nil},
  {rut: "7396777-5", name: "JUAN CARLOS FLANDEZ VELASQUEZ", unity: "RECEPCIONISTA ", charge: "UNIDAD DE SERVICIOS GENERALES", email: "jflandez@goredelosrios.cl", observation: nil},
  {rut: "8877218-0", name: "YANET CECILIA ALAMOS PARRA", unity: "SECRETARIA", charge: "DEPARTAMENTO JURíDICO", email: "calamos@goredelosrios.cl", observation: nil},
  {rut: "8064383-7", name: "IVAN PERCY MADARIAGA SIERRA", unity: "SECRETARIO EJECUTIVO DEL CONSEJO REGIONAL", charge: "SECRETARíA EJECUTIVA CONSEJO REGIONAL", email: "imadariaga@goredelosrios.cl", observation: nil},
  {rut: "9455494-2", name: "EDMUNDO RICARDO URRA OSSES", unity: "FOMENTO PRODUCTIVO E INDUSTRIA", charge: "PROGRAMA FOMENTO PRODUCTIVO E INDUSTRIA", email: "eurra@goredelosrios.cl", observation: nil},
  {rut: "14437316-2", name: "ANDRES EDUARDO HERNANDEZ SANCHEZ", unity: "FOMENTO PRODUCTIVO E INDUSTRIA", charge: "PROGRAMA FOMENTO PRODUCTIVO E INDUSTRIA", email: "ahernandez@goredelosrios.cl", observation: nil},
  {rut: "8144968-6", name: "CAMILO ANTONIO DIAZ LUNA", unity: "PROGRAMA DE GESTíON TERRITORIAL ZONAS REZAGADAS", charge: "PROGRAMA DE GESTíON TERRITORIAL ZONAS REZAGADAS", email: "cdiazl@goredelosrios.cl", observation: nil},
  {rut: "13693170-9", name: "GERARDO ANTONIO TORRES TOLEDO", unity: nil, charge: "PROGRAMA DE GESTíON TERRITORIAL ZONAS REZAGADAS", email: nil, observation: nil},
  {rut: "13660490-2", name: "RICARDO ANTONIO YAÑEZ PEREDA", unity: "GESTIóN TERRITORIAL PARA ZONAS REZAGADAS", charge: "PROGRAMA DE GESTíON TERRITORIAL ZONAS REZAGADAS", email: "ryanez@goredelosrios.cl", observation: nil},
  {rut: "15304790-1", name: "LEONARDO ENRIQUE CISTERNA TELLEZ", unity: "RESIDUOS SOLIDOS", charge: "PROGRAMA RESIDUOS SóLIDOS", email: "lcisterna@goredelosrios.cl", observation: nil},
  {rut: "8403583-1", name: "JORGE ANDRES LOPEZ GALLEGOS", unity: "PROFESIONAL PROGRAMA PIRDT", charge: "PROGRAMA INFRAESTRUCTURA PARA EL DESARROLLO TERRITORIAL", email: "jlopez@goredelosrios.cl", observation: nil},
  {rut: "12994180-4", name: "MIGUEL ANGEL MARTINEZ QUILAPAN", unity: "CUARTA DIVISIóN FOMENTO PRODUCTIVO E INDUSTRIA", charge: "PROGRAMA FOMENTO PRODUCTIVO E INDUSTRIA", email: "mmartinez@goredelosrios.cl", observation: nil},
  {rut: "8651932-1", name: "JORGE BENITO RODRIGUEZ FIGUEROA", unity: "PROGRAMA DE ELECTRIFICACION RURAL", charge: "PROGRAMA ELECTRIFICACIóN RURAL", email: "JRODRIGUEZ@GOREDELOSRIOS.CL", observation: nil},
  {rut: "16040241-5", name: "JORGE ANDRES HERNANDEZ CARMONA", unity: "ORGANIZACIONES SOCIALES", charge: "ORGANIZACIONES SOCIALES", email: "jhernandezc@goredelosrios.cl", observation: nil},
  {rut: "12912389-3", name: "CRISTIAN RODRIGO MUÑOZ JARA", unity: "PROGRAMA DE INFRAESTRUCTURA PARA EL DESARROLLO TERRITORIAL", charge: "PROGRAMA INFRAESTRUCTURA PARA EL DESARROLLO TERRITORIAL", email: "cmunozj@goredelosrios.cl", observation: nil},
  {rut: "11590963-0", name: "MICHEL ANTONIO BUCHNER ASENJO", unity: "DIVISIóN DE PLANIFICACIóN Y DESARROLLO REGIONAL ", charge: "DIVISIóN DE PLANIFICACIóN Y DESARROLLO REGIONAL", email: "mbuchner@goredelosrios.cl", observation: nil},
  {rut: "10906147-6", name: "JUAN JAVIER ROCHA AGUILERA", unity: "ORGANIZACIONES SOCIALES", charge: "ORGANIZACIONES SOCIALES", email: "jrocha@goredelosrios.cl", observation: nil},
  {rut: "10770276-8", name: "JAIME SEBASTIAN LIENLAF LIENLAF", unity: "UNIDAD DE PARTICIPACIóN CIUDADANA", charge: "UNIDAD DE PARTICIPACIóN CIUDADANA", email: "jlienlaf@goredelosrios.cl", observation: nil},
  {rut: "13519951-6", name: "CHRISTIAN ALEX MANSILLA CUEVAS", unity: "PREVENCIóN DE RIESGOS", charge: "UNIDAD DE GESTIóN ESTRATéGICA INSTITUCIONAL", email: "cmansilla@goredelosrios.cl", observation: nil},
  {rut: "15588550-5", name: "CRISTIAN ANDRES CARDENAS CARDENAS", unity: "UNIDAD DE SUBVENCIONES", charge: "UNIDAD DE SUBVENCIONES", email: "ccardenas@goredelosrios.cl", observation: nil},
  {rut: "6530889-4", name: "ALEJANDRO EDUARDO KOHLER VARGAS", unity: "ORGANIZACIONES SOCIALES ", charge: "ORGANIZACIONES SOCIALES", email: "AKOHLER@GOREDELOSRIOS.CL", observation: nil},
  {rut: "12594703-4", name: "VICTOR ROLANDO CARRILLO MIRANDA", unity: "APOYO CONTABLE EN DPTO. DE FINANZAS", charge: "DEPARTAMENTO DE FINANZAS", email: "vcarrillo@goredelosrios.cl", observation: nil},
  {rut: "10105574-4", name: "PATRICIO MARCELO MEDINA CARDENAS", unity: "ORGANIZACIONES SOCIALES", charge: "ORGANIZACIONES SOCIALES", email: "mmedina@goredelosrios.cl", observation: nil},
  {rut: "15262076-4", name: "CRISTIAN ALEJANDRO AGUILAR PEREIRA", unity: "HONORARIOS DPTO. DE FINANZAS", charge: "DEPARTAMENTO DE FINANZAS", email: "caguilar@goredelosrios.cl", observation: nil},
  {rut: "17864087-9", name: "FRANCISCO ANDRES MUÑOZ SEPULVEDA", unity: "DIVISIóN ANáLISIS Y CONTROL DE GESTIóN", charge: "DIVISIóN DE ANáLISIS Y CONTROL DE GESTIóN", email: "fmunoz@goredelosrios.cl", observation: nil},
  {rut: "8760148-K", name: "LUIS ARTURO CANO SILVA", unity: "GABINETE", charge: "GABINETE Y COMUNICACIóN", email: "lcano@goredelosrios.cl", observation: nil},
  {rut: "15549129-9", name: "MARCO ANTONIO MATTAR SILVA", unity: "ORGANIZACIONES SOCIALES", charge: "ORGANIZACIONES SOCIALES", email: "mmattar@goredelosrios.cl", observation: nil},
  {rut: "10353108-K", name: "CARLOS PATRICIO ULLOA HEINSOHN", unity: "UNIDAD DE PARTICIPACIóN CIUDADANA", charge: "UNIDAD DE PARTICIPACIóN CIUDADANA", email: "pulloa@goredelosrios.cl", observation: nil},
  {rut: "17810035-1", name: "VICTOR ANDRES TORREJON BARAHONA", unity: "ORGANIZACIONES SOCIALES", charge: "ORGANIZACIONES SOCIALES", email: "vtorrejon@goredelosrios.cl", observation: nil},
  {rut: "12432529-3", name: "JOSE LUIS MEZA MEZA", unity: "RECEPCIONISTA SEDE DEL CONSEJO REGIONAL DE LOS RíOS", charge: "SECRETARíA EJECUTIVA CONSEJO REGIONAL", email: "jmeza@goredelosrios.cl", observation: nil},
  {rut: "17358776-7", name: "LUCAS MATEO SANDOVAL FARIAS", unity: "UNIDAD DE SUBVENCIONES", charge: "UNIDAD DE SUBVENCIONES", email: nil, observation: nil},
  {rut: "12988217-4", name: "SUSAN DEL CARMEN FLORES VINETT", unity: "PROGRAMA FOMENTO PRODUCTIVO E INDUSTRIA", charge: "PROGRAMA FOMENTO PRODUCTIVO E INDUSTRIA", email: "sflores@goredelosrios.cl", observation: nil},
  {rut: "14348515-3", name: "KARIN WALESKA RAMIREZ MUÑOZ", unity: "PROGRAMA DE GESTIóN TERRITORIAL ZONAS REZAGADAS", charge: "PROGRAMA DE GESTíON TERRITORIAL ZONAS REZAGADAS", email: "kramirez@goredelosrios.cl", observation: nil},
  {rut: "16847585-3", name: "GLORIA VALESKA BARRIA SALAS", unity: "UNIDAD FRIL", charge: "UNIDAD FRIL", email: "vbarria@goredelosrios.cl", observation: nil},
  {rut: "16806754-2", name: "PAOLA ALEJANDRA GONZALEZ BURGOS", unity: "PROFESIONAL DE APOYO PROGRAMA PIRDT", charge: "PROGRAMA INFRAESTRUCTURA PARA EL DESARROLLO TERRITORIAL", email: "pgonzalez@goredelosrios.cl", observation: nil},
  {rut: "8886414-K", name: "LAURA MARLENE RAMIREZ MUÑOZ", unity: "PIRDT", charge: "PROGRAMA INFRAESTRUCTURA PARA EL DESARROLLO TERRITORIAL", email: "lramirez@goredelosrios.cl", observation: nil},
  {rut: "16805311-8", name: "CATALINA ANDREA PÉREZ SANTIBÁÑEZ", unity: "PROGRAMA SANEAMIENTO SANITARIO", charge: "PROGRAMA SANEAMIENTO SANITARIO", email: "cperezs@goredelosrios.cl", observation: nil},
  {rut: "7441126-6", name: "PATRICIA VERONICA HENRIQUEZ GUTIERREZ", unity: "HONORARIO SANEAMIENTO SANITARIO", charge: "PROGRAMA SANEAMIENTO SANITARIO", email: "phenriquez@goredelosrios.cl", observation: nil},
  {rut: "11837272-7", name: "CLAUDIA ALEJANDRA VALLEFIN CARVALLO", unity: "SECRETARIA PRESIDENTE CONSEJO REGIONAL", charge: "SECRETARíA EJECUTIVA CONSEJO REGIONAL", email: "cvallefin@goredelosrios.cl", observation: nil},
  {rut: "7059367-K", name: "GLADYS DEL CARMEN JARAMILLO CACERES", unity: "ORGANIZACIONES SOCIALES", charge: "ORGANIZACIONES SOCIALES", email: "gjaramillo@goredelosrios.cl", observation: nil},
  {rut: "14523919-2", name: "SANDRA JEANETTE RIFFO  SILVA", unity: "UNIDAD FRIL", charge: "UNIDAD FRIL", email: "sriffo@goredelosrios.cl", observation: nil},
  {rut: "13815455-6", name: "CARLA MARIAN VARGAS PELLET", unity: "ASESORÍA UNIDAD DE SERVICIOS GENERALES", charge: "DEPARTAMENTO DE FINANZAS", email: "cvargasp@goredelosrios.cl", observation: nil},
  {rut: "13821606-3", name: "JÉSSICA KARINA AZÓCAR FONTEALBA", unity: "HONORARIO CORE", charge: "SECRETARíA EJECUTIVA CONSEJO REGIONAL", email: "kekazocar@yahoo.es", observation: nil},
  {rut: "17963270-5", name: "CAMILA IZABO ULLOA DELGADO", unity: "DEPARTAMENTO DE PERSONAL", charge: "DEPARTAMENTO DE PERSONAL", email: "culloa@goredelosrios.cl", observation: nil}
])
